clone:
  depth: full

pipelines:
  branches:
    main:
      - step:
          name: Create the tarball to push to Heroku
          script:
            - git archive --format=tar.gz main -o test-tac.tar.gz
          artifacts:
            - test-tac.tar.gz
      - step:
          name: Deploy to Heroku
          script:
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: "test-tac.tar.gz"
  custom:
    run-command:
      - variables:
        - name: CUSTOM_COMMAND
      - step:
          name: "Run command"
          script:
            - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            - heroku run $CUSTOM_COMMAND --app test-tac

    run-heroku-command:
      - variables:
        - name: CUSTOM_COMMAND
      - step:
          name: "Run heroku command"
          script:
            - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            - heroku $CUSTOM_COMMAND --app test-tac
